<?php
/**
 * Brand Directory — ProductPro
 * Auto-generated from Fantasies Boutique brand spreadsheet.
 * 286 brands, sorted by value (priority).
 *
 * @package ProductPro
 */

if ( ! defined( 'ABSPATH' ) ) exit;

function sdn_brand_directory() {
    return array(
        array( 'name' => 'Biird', 'slug' => 'biird', 'initials' => 'B', 'value' => 10 ),
        array( 'name' => 'Bijoux Indiscrets', 'slug' => 'bijoux-indiscrets', 'initials' => 'BI', 'value' => 10 ),
        array( 'name' => 'Fifty Shades of Grey', 'slug' => 'fifty-shades-of-grey', 'initials' => 'FSO', 'value' => 10 ),
        array( 'name' => 'Le Wand', 'slug' => 'le-wand', 'initials' => 'LW', 'value' => 10 ),
        array( 'name' => 'Lelo', 'slug' => 'lelo', 'initials' => 'L', 'value' => 10 ),
        array( 'name' => 'Liberator', 'slug' => 'liberator', 'initials' => 'L', 'value' => 10 ),
        array( 'name' => 'Allure Lingerie', 'slug' => 'allure-lingerie', 'initials' => 'AL', 'value' => 9 ),
        array( 'name' => 'BeWicked', 'slug' => 'bewicked', 'initials' => 'B', 'value' => 9 ),
        array( 'name' => 'Blush', 'slug' => 'blush', 'initials' => 'B', 'value' => 9 ),
        array( 'name' => 'Crave', 'slug' => 'crave', 'initials' => 'C', 'value' => 9 ),
        array( 'name' => 'DYSO', 'slug' => 'dyso', 'initials' => 'D', 'value' => 9 ),
        array( 'name' => 'Eye of Love', 'slug' => 'eye-of-love', 'initials' => 'EOL', 'value' => 9 ),
        array( 'name' => 'Fantasy Lingerie', 'slug' => 'fantasy-lingerie', 'initials' => 'FL', 'value' => 9 ),
        array( 'name' => 'FemmeFunn', 'slug' => 'femmefunn', 'initials' => 'F', 'value' => 9 ),
        array( 'name' => 'High On Love', 'slug' => 'high-on-love', 'initials' => 'HOL', 'value' => 9 ),
        array( 'name' => 'Magic Wand', 'slug' => 'magic-wand', 'initials' => 'MW', 'value' => 9 ),
        array( 'name' => 'Neo Sensual', 'slug' => 'neo-sensual', 'initials' => 'NS', 'value' => 9 ),
        array( 'name' => 'Neva Nude', 'slug' => 'neva-nude', 'initials' => 'NN', 'value' => 9 ),
        array( 'name' => 'Nexus', 'slug' => 'nexus', 'initials' => 'N', 'value' => 9 ),
        array( 'name' => 'NJoy', 'slug' => 'njoy', 'initials' => 'N', 'value' => 9 ),
        array( 'name' => 'Nuud', 'slug' => 'nuud', 'initials' => 'N', 'value' => 9 ),
        array( 'name' => 'Ple\'sur', 'slug' => 'ple-sur', 'initials' => 'P', 'value' => 9 ),
        array( 'name' => 'Sportsheets', 'slug' => 'sportsheets', 'initials' => 'S', 'value' => 9 ),
        array( 'name' => 'SVibe - Snail Vibe', 'slug' => 'svibe-snail-vibe', 'initials' => 'S-S', 'value' => 9 ),
        array( 'name' => 'Tantus', 'slug' => 'tantus', 'initials' => 'T', 'value' => 9 ),
        array( 'name' => 'Tenga', 'slug' => 'tenga', 'initials' => 'T', 'value' => 9 ),
        array( 'name' => 'Twisted Wears', 'slug' => 'twisted-wears', 'initials' => 'TW', 'value' => 9 ),
        array( 'name' => 'We-Vibe', 'slug' => 'we-vibe', 'initials' => 'W', 'value' => 9 ),
        array( 'name' => 'Wicked', 'slug' => 'wicked', 'initials' => 'W', 'value' => 9 ),
        array( 'name' => 'Womanizer', 'slug' => 'womanizer', 'initials' => 'W', 'value' => 9 ),
        array( 'name' => 'B-Vibe', 'slug' => 'b-vibe', 'initials' => 'B', 'value' => 8 ),
        array( 'name' => 'Doc Johnson', 'slug' => 'doc-johnson', 'initials' => 'DJ', 'value' => 8 ),
        array( 'name' => 'Dreamgirl', 'slug' => 'dreamgirl', 'initials' => 'D', 'value' => 8 ),
        array( 'name' => 'Forto', 'slug' => 'forto', 'initials' => 'F', 'value' => 8 ),
        array( 'name' => 'Gender X', 'slug' => 'gender-x', 'initials' => 'GX', 'value' => 8 ),
        array( 'name' => 'Global Novelties', 'slug' => 'global-novelties', 'initials' => 'GN', 'value' => 8 ),
        array( 'name' => 'Intimate Earth', 'slug' => 'intimate-earth', 'initials' => 'IE', 'value' => 8 ),
        array( 'name' => 'Je Joue', 'slug' => 'je-joue', 'initials' => 'JJ', 'value' => 8 ),
        array( 'name' => 'Leg Avenue', 'slug' => 'leg-avenue', 'initials' => 'LA', 'value' => 8 ),
        array( 'name' => 'Nu Sensuelle', 'slug' => 'nu-sensuelle', 'initials' => 'NS', 'value' => 8 ),
        array( 'name' => 'Oh La La Cheri', 'slug' => 'oh-la-la-cheri', 'initials' => 'OLL', 'value' => 8 ),
        array( 'name' => 'Playboy', 'slug' => 'playboy', 'initials' => 'P', 'value' => 8 ),
        array( 'name' => 'Playground', 'slug' => 'playground', 'initials' => 'P', 'value' => 8 ),
        array( 'name' => 'System JO', 'slug' => 'system-jo', 'initials' => 'SJ', 'value' => 8 ),
        array( 'name' => 'VeDO', 'slug' => 'vedo', 'initials' => 'V', 'value' => 8 ),
        array( 'name' => 'VibePad', 'slug' => 'vibepad', 'initials' => 'V', 'value' => 8 ),
        array( 'name' => 'WAP', 'slug' => 'wap', 'initials' => 'W', 'value' => 8 ),
        array( 'name' => 'Wet For Her', 'slug' => 'wet-for-her', 'initials' => 'WFH', 'value' => 8 ),
        array( 'name' => 'Zeus', 'slug' => 'zeus', 'initials' => 'Z', 'value' => 8 ),
        array( 'name' => 'Coochy', 'slug' => 'coochy', 'initials' => 'C', 'value' => 7 ),
        array( 'name' => 'Coquette', 'slug' => 'coquette', 'initials' => 'C', 'value' => 7 ),
        array( 'name' => 'Creative Conceptions', 'slug' => 'creative-conceptions', 'initials' => 'CC', 'value' => 7 ),
        array( 'name' => 'Curve Novelties', 'slug' => 'curve-novelties', 'initials' => 'CN', 'value' => 7 ),
        array( 'name' => 'Dame', 'slug' => 'dame', 'initials' => 'D', 'value' => 7 ),
        array( 'name' => 'Doxy', 'slug' => 'doxy', 'initials' => 'D', 'value' => 7 ),
        array( 'name' => 'Earthly Body', 'slug' => 'earthly-body', 'initials' => 'EB', 'value' => 7 ),
        array( 'name' => 'Electric Eel', 'slug' => 'electric-eel', 'initials' => 'EE', 'value' => 7 ),
        array( 'name' => 'Elephant 9000', 'slug' => 'elephant-9000', 'initials' => 'E9', 'value' => 7 ),
        array( 'name' => 'Evolved', 'slug' => 'evolved', 'initials' => 'E', 'value' => 7 ),
        array( 'name' => 'Exsens', 'slug' => 'exsens', 'initials' => 'E', 'value' => 7 ),
        array( 'name' => 'Flintts Mints', 'slug' => 'flintts-mints', 'initials' => 'FM', 'value' => 7 ),
        array( 'name' => 'Fun Factory', 'slug' => 'fun-factory', 'initials' => 'FF', 'value' => 7 ),
        array( 'name' => 'Geeky & Kinky', 'slug' => 'geeky-kinky', 'initials' => 'G&K', 'value' => 7 ),
        array( 'name' => 'Glyde Condoms', 'slug' => 'glyde-condoms', 'initials' => 'GC', 'value' => 7 ),
        array( 'name' => 'Gold Lion', 'slug' => 'gold-lion', 'initials' => 'GL', 'value' => 7 ),
        array( 'name' => 'Happy Rabbit', 'slug' => 'happy-rabbit', 'initials' => 'HR', 'value' => 7 ),
        array( 'name' => 'Harper Collins', 'slug' => 'harper-collins', 'initials' => 'HC', 'value' => 7 ),
        array( 'name' => 'ID Lubricants', 'slug' => 'id-lubricants', 'initials' => 'IL', 'value' => 7 ),
        array( 'name' => 'Jimmyjane', 'slug' => 'jimmyjane', 'initials' => 'J', 'value' => 7 ),
        array( 'name' => 'La Nua', 'slug' => 'la-nua', 'initials' => 'LN', 'value' => 7 ),
        array( 'name' => 'Magic Silk', 'slug' => 'magic-silk', 'initials' => 'MS', 'value' => 7 ),
        array( 'name' => 'Me You Us', 'slug' => 'me-you-us', 'initials' => 'MYU', 'value' => 7 ),
        array( 'name' => 'Penguin', 'slug' => 'penguin', 'initials' => 'P', 'value' => 7 ),
        array( 'name' => 'Pjur', 'slug' => 'pjur', 'initials' => 'P', 'value' => 7 ),
        array( 'name' => 'Platinum Wood-E', 'slug' => 'platinum-wood-e', 'initials' => 'PW', 'value' => 7 ),
        array( 'name' => 'Rouge Garments', 'slug' => 'rouge-garments', 'initials' => 'RG', 'value' => 7 ),
        array( 'name' => 'Screaming O', 'slug' => 'screaming-o', 'initials' => 'SO', 'value' => 7 ),
        array( 'name' => 'Selopa', 'slug' => 'selopa', 'initials' => 'S', 'value' => 7 ),
        array( 'name' => 'Sensuva', 'slug' => 'sensuva', 'initials' => 'S', 'value' => 7 ),
        array( 'name' => 'Sex Chocolates', 'slug' => 'sex-chocolates', 'initials' => 'SC', 'value' => 7 ),
        array( 'name' => 'Sheets of San Francisco', 'slug' => 'sheets-of-san-francisco', 'initials' => 'SOS', 'value' => 7 ),
        array( 'name' => 'Shibari', 'slug' => 'shibari', 'initials' => 'S', 'value' => 7 ),
        array( 'name' => 'Spartacus', 'slug' => 'spartacus', 'initials' => 'S', 'value' => 7 ),
        array( 'name' => 'SportLube', 'slug' => 'sportlube', 'initials' => 'S', 'value' => 7 ),
        array( 'name' => 'Swiss Navy', 'slug' => 'swiss-navy', 'initials' => 'SN', 'value' => 7 ),
        array( 'name' => 'The Cowgirl', 'slug' => 'the-cowgirl', 'initials' => 'TC', 'value' => 7 ),
        array( 'name' => 'The Male Rose', 'slug' => 'the-male-rose', 'initials' => 'TMR', 'value' => 7 ),
        array( 'name' => 'Tickle Kitty', 'slug' => 'tickle-kitty', 'initials' => 'TK', 'value' => 7 ),
        array( 'name' => 'Toca', 'slug' => 'toca', 'initials' => 'T', 'value' => 7 ),
        array( 'name' => 'Together Toy', 'slug' => 'together-toy', 'initials' => 'TT', 'value' => 7 ),
        array( 'name' => 'Wood Rocket', 'slug' => 'wood-rocket', 'initials' => 'WR', 'value' => 7 ),
        array( 'name' => 'Blush Avant', 'slug' => 'blush-avant', 'initials' => 'BA', 'value' => 6 ),
        array( 'name' => 'Ball and Chain', 'slug' => 'ball-and-chain', 'initials' => 'BAC', 'value' => 6 ),
        array( 'name' => 'Balldo', 'slug' => 'balldo', 'initials' => 'B', 'value' => 6 ),
        array( 'name' => 'Banana Pants', 'slug' => 'banana-pants', 'initials' => 'BP', 'value' => 6 ),
        array( 'name' => 'Bathmate', 'slug' => 'bathmate', 'initials' => 'B', 'value' => 6 ),
        array( 'name' => 'Boneyard', 'slug' => 'boneyard', 'initials' => 'B', 'value' => 6 ),
        array( 'name' => 'Bristols', 'slug' => 'bristols', 'initials' => 'B', 'value' => 6 ),
        array( 'name' => 'Cute Little Fuckers', 'slug' => 'cute-little-fuckers', 'initials' => 'CLF', 'value' => 6 ),
        array( 'name' => 'Deia', 'slug' => 'deia', 'initials' => 'D', 'value' => 6 ),
        array( 'name' => 'Dr. Tush\'s', 'slug' => 'dr-tush-s', 'initials' => 'DT', 'value' => 6 ),
        array( 'name' => 'Elvie', 'slug' => 'elvie', 'initials' => 'E', 'value' => 6 ),
        array( 'name' => 'Emojibator', 'slug' => 'emojibator', 'initials' => 'E', 'value' => 6 ),
        array( 'name' => 'Eroscillator', 'slug' => 'eroscillator', 'initials' => 'E', 'value' => 6 ),
        array( 'name' => 'Foxtails', 'slug' => 'foxtails', 'initials' => 'F', 'value' => 6 ),
        array( 'name' => 'Hachette', 'slug' => 'hachette', 'initials' => 'H', 'value' => 6 ),
        array( 'name' => 'Hot Octopuss', 'slug' => 'hot-octopuss', 'initials' => 'HO', 'value' => 6 ),
        array( 'name' => 'Hott Products', 'slug' => 'hott-products', 'initials' => 'HP', 'value' => 6 ),
        array( 'name' => 'Icon Brands', 'slug' => 'icon-brands', 'initials' => 'IB', 'value' => 6 ),
        array( 'name' => 'IIngram', 'slug' => 'iingram', 'initials' => 'I', 'value' => 6 ),
        array( 'name' => 'It\'s the Bomb', 'slug' => 'it-s-the-bomb', 'initials' => 'ITB', 'value' => 6 ),
        array( 'name' => 'JAVA Skin Care', 'slug' => 'java-skin-care', 'initials' => 'JSC', 'value' => 6 ),
        array( 'name' => 'JJC Production Design', 'slug' => 'jjc-production-design', 'initials' => 'JPD', 'value' => 6 ),
        array( 'name' => 'Kheper Games', 'slug' => 'kheper-games', 'initials' => 'KG', 'value' => 6 ),
        array( 'name' => 'Kixies', 'slug' => 'kixies', 'initials' => 'K', 'value' => 6 ),
        array( 'name' => 'LA Pump', 'slug' => 'la-pump', 'initials' => 'LP', 'value' => 6 ),
        array( 'name' => 'Little Genie', 'slug' => 'little-genie', 'initials' => 'LG', 'value' => 6 ),
        array( 'name' => 'Lovense', 'slug' => 'lovense', 'initials' => 'L', 'value' => 6 ),
        array( 'name' => 'Lust Fetish', 'slug' => 'lust-fetish', 'initials' => 'LF', 'value' => 6 ),
        array( 'name' => 'Luv Inc', 'slug' => 'luv-inc', 'initials' => 'LI', 'value' => 6 ),
        array( 'name' => 'Male Power', 'slug' => 'male-power', 'initials' => 'MP', 'value' => 6 ),
        array( 'name' => 'Nasstoys', 'slug' => 'nasstoys', 'initials' => 'N', 'value' => 6 ),
        array( 'name' => 'OhMiBod', 'slug' => 'ohmibod', 'initials' => 'O', 'value' => 6 ),
        array( 'name' => 'Olivia\'s Boudoir', 'slug' => 'olivia-s-boudoir', 'initials' => 'OB', 'value' => 6 ),
        array( 'name' => 'Oxballs', 'slug' => 'oxballs', 'initials' => 'O', 'value' => 6 ),
        array( 'name' => 'PDX Brands', 'slug' => 'pdx-brands', 'initials' => 'PB', 'value' => 6 ),
        array( 'name' => 'Perfect Fit', 'slug' => 'perfect-fit', 'initials' => 'PF', 'value' => 6 ),
        array( 'name' => 'Pipedream', 'slug' => 'pipedream', 'initials' => 'P', 'value' => 6 ),
        array( 'name' => 'Rhino', 'slug' => 'rhino', 'initials' => 'R', 'value' => 6 ),
        array( 'name' => 'Rock Candy', 'slug' => 'rock-candy', 'initials' => 'RC', 'value' => 6 ),
        array( 'name' => 'Rosy Gold', 'slug' => 'rosy-gold', 'initials' => 'RG', 'value' => 6 ),
        array( 'name' => 'Royal Condom', 'slug' => 'royal-condom', 'initials' => 'RC', 'value' => 6 ),
        array( 'name' => 'Shots', 'slug' => 'shots', 'initials' => 'S', 'value' => 6 ),
        array( 'name' => 'Si Novelties', 'slug' => 'si-novelties', 'initials' => 'SN', 'value' => 6 ),
        array( 'name' => 'Sliquid', 'slug' => 'sliquid', 'initials' => 'S', 'value' => 6 ),
        array( 'name' => 'Snail Vibe - SVibe', 'slug' => 'snail-vibe-svibe', 'initials' => 'SV-', 'value' => 6 ),
        array( 'name' => 'Spunk Lube', 'slug' => 'spunk-lube', 'initials' => 'SL', 'value' => 6 ),
        array( 'name' => 'TheVibed', 'slug' => 'thevibed', 'initials' => 'T', 'value' => 6 ),
        array( 'name' => 'Top Cat', 'slug' => 'top-cat', 'initials' => 'TC', 'value' => 6 ),
        array( 'name' => 'Total Stealth', 'slug' => 'total-stealth', 'initials' => 'TS', 'value' => 6 ),
        array( 'name' => 'Tristan Taormino', 'slug' => 'tristan-taormino', 'initials' => 'TT', 'value' => 6 ),
        array( 'name' => 'Velv\'Or', 'slug' => 'velv-or', 'initials' => 'V', 'value' => 6 ),
        array( 'name' => 'VERS', 'slug' => 'vers', 'initials' => 'V', 'value' => 6 ),
        array( 'name' => 'Viotec', 'slug' => 'viotec', 'initials' => 'V', 'value' => 6 ),
        array( 'name' => 'Warm Inc', 'slug' => 'warm-inc', 'initials' => 'WI', 'value' => 6 ),
        array( 'name' => 'XR Brands', 'slug' => 'xr-brands', 'initials' => 'XB', 'value' => 6 ),
        array( 'name' => 'Le Desir', 'slug' => 'le-desir', 'initials' => 'LD', 'value' => 5 ),
        array( 'name' => 'Adam & Eve', 'slug' => 'adam-eve', 'initials' => 'A&E', 'value' => 5 ),
        array( 'name' => 'AH! YES', 'slug' => 'ah-yes', 'initials' => 'AY', 'value' => 5 ),
        array( 'name' => 'Aloe Cadabra', 'slug' => 'aloe-cadabra', 'initials' => 'AC', 'value' => 5 ),
        array( 'name' => 'Ammo Books', 'slug' => 'ammo-books', 'initials' => 'AB', 'value' => 5 ),
        array( 'name' => 'Aneros', 'slug' => 'aneros', 'initials' => 'A', 'value' => 5 ),
        array( 'name' => 'Arcwave', 'slug' => 'arcwave', 'initials' => 'A', 'value' => 5 ),
        array( 'name' => 'BMS', 'slug' => 'bms', 'initials' => 'B', 'value' => 5 ),
        array( 'name' => 'Body Action', 'slug' => 'body-action', 'initials' => 'BA', 'value' => 5 ),
        array( 'name' => 'Bonks', 'slug' => 'bonks', 'initials' => 'B', 'value' => 5 ),
        array( 'name' => 'Classic Brands', 'slug' => 'classic-brands', 'initials' => 'CB', 'value' => 5 ),
        array( 'name' => 'Clone-A-Willy', 'slug' => 'clone-a-willy', 'initials' => 'C', 'value' => 5 ),
        array( 'name' => 'NS Novelties Cosmo', 'slug' => 'ns-novelties-cosmo', 'initials' => 'NNC', 'value' => 5 ),
        array( 'name' => 'Du', 'slug' => 'du', 'initials' => 'D', 'value' => 5 ),
        array( 'name' => 'Elbow Grease', 'slug' => 'elbow-grease', 'initials' => 'EG', 'value' => 5 ),
        array( 'name' => 'FashionCraft', 'slug' => 'fashioncraft', 'initials' => 'F', 'value' => 5 ),
        array( 'name' => 'ffix - FemmeFunn', 'slug' => 'ffix-femmefunn', 'initials' => 'F-F', 'value' => 5 ),
        array( 'name' => 'Forum Novelties', 'slug' => 'forum-novelties', 'initials' => 'FN', 'value' => 5 ),
        array( 'name' => 'Fuck Water', 'slug' => 'fuck-water', 'initials' => 'FW', 'value' => 5 ),
        array( 'name' => 'Fuzu', 'slug' => 'fuzu', 'initials' => 'F', 'value' => 5 ),
        array( 'name' => 'Gun Oil', 'slug' => 'gun-oil', 'initials' => 'GO', 'value' => 5 ),
        array( 'name' => 'GVibe', 'slug' => 'gvibe', 'initials' => 'G', 'value' => 5 ),
        array( 'name' => 'Honey Play Box', 'slug' => 'honey-play-box', 'initials' => 'HPB', 'value' => 5 ),
        array( 'name' => 'Kingman Industries', 'slug' => 'kingman-industries', 'initials' => 'KI', 'value' => 5 ),
        array( 'name' => 'Knock Knock', 'slug' => 'knock-knock', 'initials' => 'KK', 'value' => 5 ),
        array( 'name' => 'KushKards', 'slug' => 'kushkards', 'initials' => 'K', 'value' => 5 ),
        array( 'name' => 'Lifestyles', 'slug' => 'lifestyles', 'initials' => 'L', 'value' => 5 ),
        array( 'name' => 'Lola Milani', 'slug' => 'lola-milani', 'initials' => 'LM', 'value' => 5 ),
        array( 'name' => 'Love Hamma', 'slug' => 'love-hamma', 'initials' => 'LH', 'value' => 5 ),
        array( 'name' => 'Love Not War', 'slug' => 'love-not-war', 'initials' => 'LNW', 'value' => 5 ),
        array( 'name' => 'Lovely Planet', 'slug' => 'lovely-planet', 'initials' => 'LP', 'value' => 5 ),
        array( 'name' => 'Lunatic Ink', 'slug' => 'lunatic-ink', 'initials' => 'LI', 'value' => 5 ),
        array( 'name' => 'MaleBasics', 'slug' => 'malebasics', 'initials' => 'M', 'value' => 5 ),
        array( 'name' => 'Marathon', 'slug' => 'marathon', 'initials' => 'M', 'value' => 5 ),
        array( 'name' => 'Nalone', 'slug' => 'nalone', 'initials' => 'N', 'value' => 5 ),
        array( 'name' => 'Nectar', 'slug' => 'nectar', 'initials' => 'N', 'value' => 5 ),
        array( 'name' => 'NS Novelties', 'slug' => 'ns-novelties', 'initials' => 'NN', 'value' => 5 ),
        array( 'name' => 'OhNut', 'slug' => 'ohnut', 'initials' => 'O', 'value' => 5 ),
        array( 'name' => 'Omax Health', 'slug' => 'omax-health', 'initials' => 'OH', 'value' => 5 ),
        array( 'name' => 'ONE', 'slug' => 'one', 'initials' => 'O', 'value' => 5 ),
        array( 'name' => 'Pastease', 'slug' => 'pastease', 'initials' => 'P', 'value' => 5 ),
        array( 'name' => 'Personal Fav', 'slug' => 'personal-fav', 'initials' => 'PF', 'value' => 5 ),
        array( 'name' => 'Peter Pauper Press', 'slug' => 'peter-pauper-press', 'initials' => 'PPP', 'value' => 5 ),
        array( 'name' => 'PHS International', 'slug' => 'phs-international', 'initials' => 'PI', 'value' => 5 ),
        array( 'name' => 'Pink Pussycat', 'slug' => 'pink-pussycat', 'initials' => 'PP', 'value' => 5 ),
        array( 'name' => 'Pink Sensuals', 'slug' => 'pink-sensuals', 'initials' => 'PS', 'value' => 5 ),
        array( 'name' => 'Prowler', 'slug' => 'prowler', 'initials' => 'P', 'value' => 5 ),
        array( 'name' => 'Prowler RED', 'slug' => 'prowler-red', 'initials' => 'PR', 'value' => 5 ),
        array( 'name' => 'Rianne S', 'slug' => 'rianne-s', 'initials' => 'RS', 'value' => 5 ),
        array( 'name' => 'Rock Solid', 'slug' => 'rock-solid', 'initials' => 'RS', 'value' => 5 ),
        array( 'name' => 'Rocks-Off', 'slug' => 'rocks-off', 'initials' => 'R', 'value' => 5 ),
        array( 'name' => 'ROMP', 'slug' => 'romp', 'initials' => 'R', 'value' => 5 ),
        array( 'name' => 'Ruff Doggie Styles', 'slug' => 'ruff-doggie-styles', 'initials' => 'RDS', 'value' => 5 ),
        array( 'name' => 'SexGrease', 'slug' => 'sexgrease', 'initials' => 'S', 'value' => 5 ),
        array( 'name' => 'Sexsation', 'slug' => 'sexsation', 'initials' => 'S', 'value' => 5 ),
        array( 'name' => 'Simon & Schuster', 'slug' => 'simon-schuster', 'initials' => 'S&S', 'value' => 5 ),
        array( 'name' => 'Sinclair Intimacy Institute', 'slug' => 'sinclair-intimacy-institute', 'initials' => 'SII', 'value' => 5 ),
        array( 'name' => 'Sleev', 'slug' => 'sleev', 'initials' => 'S', 'value' => 5 ),
        array( 'name' => 'Slippery Stuff', 'slug' => 'slippery-stuff', 'initials' => 'SS', 'value' => 5 ),
        array( 'name' => 'SOS Distribution', 'slug' => 'sos-distribution', 'initials' => 'SD', 'value' => 5 ),
        array( 'name' => 'Sourcebooks', 'slug' => 'sourcebooks', 'initials' => 'S', 'value' => 5 ),
        array( 'name' => 'SpareParts', 'slug' => 'spareparts', 'initials' => 'S', 'value' => 5 ),
        array( 'name' => 'Stealth Shaft Support', 'slug' => 'stealth-shaft-support', 'initials' => 'SSS', 'value' => 5 ),
        array( 'name' => 'Stockroom', 'slug' => 'stockroom', 'initials' => 'S', 'value' => 5 ),
        array( 'name' => 'Stud 100', 'slug' => 'stud-100', 'initials' => 'S1', 'value' => 5 ),
        array( 'name' => 'Sweet Spot Labs', 'slug' => 'sweet-spot-labs', 'initials' => 'SSL', 'value' => 5 ),
        array( 'name' => 'Voodoo', 'slug' => 'voodoo', 'initials' => 'V', 'value' => 5 ),
        array( 'name' => 'VUSH', 'slug' => 'vush', 'initials' => 'V', 'value' => 5 ),
        array( 'name' => 'You2Toys', 'slug' => 'you2toys', 'initials' => 'Y', 'value' => 5 ),
        array( 'name' => 'Zero Tolerance', 'slug' => 'zero-tolerance', 'initials' => 'ZT', 'value' => 5 ),
        array( 'name' => 'CRUIZR', 'slug' => 'cruizr', 'initials' => 'C', 'value' => 5 ),
        array( 'name' => 'Crystal Delights', 'slug' => 'crystal-delights', 'initials' => 'CD', 'value' => 5 ),
        array( 'name' => 'Demon Kat', 'slug' => 'demon-kat', 'initials' => 'DK', 'value' => 5 ),
        array( 'name' => 'Sweetums', 'slug' => 'sweetums', 'initials' => 'S', 'value' => 5 ),
        array( 'name' => 'Astroglide', 'slug' => 'astroglide', 'initials' => 'A', 'value' => 4 ),
        array( 'name' => 'Autoblow', 'slug' => 'autoblow', 'initials' => 'A', 'value' => 4 ),
        array( 'name' => 'B Swish', 'slug' => 'b-swish', 'initials' => 'BS', 'value' => 4 ),
        array( 'name' => 'Barely Bare', 'slug' => 'barely-bare', 'initials' => 'BB', 'value' => 4 ),
        array( 'name' => 'Bednar International', 'slug' => 'bednar-international', 'initials' => 'BI', 'value' => 4 ),
        array( 'name' => 'Bella', 'slug' => 'bella', 'initials' => 'B', 'value' => 4 ),
        array( 'name' => 'Beloved', 'slug' => 'beloved', 'initials' => 'B', 'value' => 4 ),
        array( 'name' => 'Beverly Hills Naughty Girl', 'slug' => 'beverly-hills-naughty-girl', 'initials' => 'BHN', 'value' => 4 ),
        array( 'name' => 'Body Arts Ink', 'slug' => 'body-arts-ink', 'initials' => 'BAI', 'value' => 4 ),
        array( 'name' => 'Boy Butter', 'slug' => 'boy-butter', 'initials' => 'BB', 'value' => 4 ),
        array( 'name' => 'Cal Exotics', 'slug' => 'cal-exotics', 'initials' => 'CE', 'value' => 4 ),
        array( 'name' => 'CB-X', 'slug' => 'cb-x', 'initials' => 'C', 'value' => 4 ),
        array( 'name' => 'Center for the Intimate Arts', 'slug' => 'center-for-the-intimate-arts', 'initials' => 'CFT', 'value' => 4 ),
        array( 'name' => 'Cheeky', 'slug' => 'cheeky', 'initials' => 'C', 'value' => 4 ),
        array( 'name' => 'Chronicle', 'slug' => 'chronicle', 'initials' => 'C', 'value' => 4 ),
        array( 'name' => 'Clandestine Devices', 'slug' => 'clandestine-devices', 'initials' => 'CD', 'value' => 4 ),
        array( 'name' => 'Cleis Press', 'slug' => 'cleis-press', 'initials' => 'CP', 'value' => 4 ),
        array( 'name' => 'Clone-A-Pussy', 'slug' => 'clone-a-pussy', 'initials' => 'C', 'value' => 4 ),
        array( 'name' => 'Coconu', 'slug' => 'coconu', 'initials' => 'C', 'value' => 4 ),
        array( 'name' => 'Cousins Group', 'slug' => 'cousins-group', 'initials' => 'CG', 'value' => 4 ),
        array( 'name' => 'Deeva', 'slug' => 'deeva', 'initials' => 'D', 'value' => 4 ),
        array( 'name' => 'Duke University Press', 'slug' => 'duke-university-press', 'initials' => 'DUP', 'value' => 4 ),
        array( 'name' => 'EDC Wholesale', 'slug' => 'edc-wholesale', 'initials' => 'EW', 'value' => 4 ),
        array( 'name' => 'Energizer', 'slug' => 'energizer', 'initials' => 'E', 'value' => 4 ),
        array( 'name' => 'EngErotics', 'slug' => 'engerotics', 'initials' => 'E', 'value' => 4 ),
        array( 'name' => 'Ether', 'slug' => 'ether', 'initials' => 'E', 'value' => 4 ),
        array( 'name' => 'Eveready', 'slug' => 'eveready', 'initials' => 'E', 'value' => 4 ),
        array( 'name' => 'Golden Triangle', 'slug' => 'golden-triangle', 'initials' => 'GT', 'value' => 4 ),
        array( 'name' => 'Good Clean Love', 'slug' => 'good-clean-love', 'initials' => 'GCL', 'value' => 4 ),
        array( 'name' => 'Goofy Foot Press', 'slug' => 'goofy-foot-press', 'initials' => 'GFP', 'value' => 4 ),
        array( 'name' => 'Liquid Silk', 'slug' => 'liquid-silk', 'initials' => 'LS', 'value' => 4 ),
        array( 'name' => 'Lovehoney', 'slug' => 'lovehoney', 'initials' => 'L', 'value' => 4 ),
        array( 'name' => 'Magna-Rect', 'slug' => 'magna-rect', 'initials' => 'M', 'value' => 4 ),
        array( 'name' => 'Magnetic Poetry', 'slug' => 'magnetic-poetry', 'initials' => 'MP', 'value' => 4 ),
        array( 'name' => 'Marrakech Express (Mystic)', 'slug' => 'marrakech-express-mystic', 'initials' => 'ME(', 'value' => 4 ),
        array( 'name' => 'Maxtasy', 'slug' => 'maxtasy', 'initials' => 'M', 'value' => 4 ),
        array( 'name' => 'Migliori', 'slug' => 'migliori', 'initials' => 'M', 'value' => 4 ),
        array( 'name' => 'Mystim', 'slug' => 'mystim', 'initials' => 'M', 'value' => 4 ),
        array( 'name' => 'Naked Silk', 'slug' => 'naked-silk', 'initials' => 'NS', 'value' => 4 ),
        array( 'name' => 'NobEssence', 'slug' => 'nobessence', 'initials' => 'N', 'value' => 4 ),
        array( 'name' => 'Noir Handmade', 'slug' => 'noir-handmade', 'initials' => 'NH', 'value' => 4 ),
        array( 'name' => 'Paradise Marketing', 'slug' => 'paradise-marketing', 'initials' => 'PM', 'value' => 4 ),
        array( 'name' => 'Pretty Plugs', 'slug' => 'pretty-plugs', 'initials' => 'PP', 'value' => 4 ),
        array( 'name' => 'Privy Peach', 'slug' => 'privy-peach', 'initials' => 'PP', 'value' => 4 ),
        array( 'name' => 'Pro West Distribution', 'slug' => 'pro-west-distribution', 'initials' => 'PWD', 'value' => 4 ),
        array( 'name' => 'Probe', 'slug' => 'probe', 'initials' => 'P', 'value' => 4 ),
        array( 'name' => 'Promescent', 'slug' => 'promescent', 'initials' => 'P', 'value' => 4 ),
        array( 'name' => 'Puss & Pits', 'slug' => 'puss-pits', 'initials' => 'P&P', 'value' => 4 ),
        array( 'name' => 'Rene Rofe', 'slug' => 'rene-rofe', 'initials' => 'RR', 'value' => 4 ),
        array( 'name' => 'SexToy', 'slug' => 'sextoy', 'initials' => 'S', 'value' => 4 ),
        array( 'name' => 'Shaft', 'slug' => 'shaft', 'initials' => 'S', 'value' => 4 ),
        array( 'name' => 'SS+HE', 'slug' => 'ss-he', 'initials' => 'S', 'value' => 4 ),
        array( 'name' => 'SSCB', 'slug' => 'sscb', 'initials' => 'S', 'value' => 4 ),
        array( 'name' => 'Cyrex - ElectraStim', 'slug' => 'cyrex-electrastim', 'initials' => 'C-E', 'value' => 3 ),
        array( 'name' => 'mipole', 'slug' => 'mipole', 'initials' => 'M', 'value' => 3 ),
        array( 'name' => 'MPS', 'slug' => 'mps', 'initials' => 'M', 'value' => 3 ),
        array( 'name' => 'Myhixel', 'slug' => 'myhixel', 'initials' => 'M', 'value' => 3 ),
        array( 'name' => 'Ozone Productions', 'slug' => 'ozone-productions', 'initials' => 'OP', 'value' => 3 ),
        array( 'name' => 'Pacific Media', 'slug' => 'pacific-media', 'initials' => 'PM', 'value' => 3 ),
        array( 'name' => 'Panasonic', 'slug' => 'panasonic', 'initials' => 'P', 'value' => 3 ),
        array( 'name' => 'Paper Epiphanies', 'slug' => 'paper-epiphanies', 'initials' => 'PE', 'value' => 3 ),
        array( 'name' => 'Poseidon', 'slug' => 'poseidon', 'initials' => 'P', 'value' => 3 ),
        array( 'name' => 'Terrace Publishing', 'slug' => 'terrace-publishing', 'initials' => 'TP', 'value' => 3 ),
        array( 'name' => 'Rascal', 'slug' => 'rascal', 'initials' => 'R', 'value' => 1 ),
        array( 'name' => 'Em & Friends', 'slug' => 'em-friends', 'initials' => 'E&F', 'value' => 1 ),
        array( 'name' => 'Fixture', 'slug' => 'fixture', 'initials' => 'F', 'value' => 1 ),
    );
}

/** Recently joined brands */
function sdn_new_brands() {
    return array(
        array( 'name' => 'Biird', 'slug' => 'biird', 'initials' => 'B', 'value' => 10 ),
        array( 'name' => 'Bijoux Indiscrets', 'slug' => 'bijoux-indiscrets', 'initials' => 'BI', 'value' => 10 ),
        array( 'name' => 'Fifty Shades of Grey', 'slug' => 'fifty-shades-of-grey', 'initials' => 'FSO', 'value' => 10 ),
        array( 'name' => 'Le Wand', 'slug' => 'le-wand', 'initials' => 'LW', 'value' => 10 ),
        array( 'name' => 'Lelo', 'slug' => 'lelo', 'initials' => 'L', 'value' => 10 ),
        array( 'name' => 'Liberator', 'slug' => 'liberator', 'initials' => 'L', 'value' => 10 ),
        array( 'name' => 'Allure Lingerie', 'slug' => 'allure-lingerie', 'initials' => 'AL', 'value' => 9 ),
        array( 'name' => 'BeWicked', 'slug' => 'bewicked', 'initials' => 'B', 'value' => 9 ),
        array( 'name' => 'Blush', 'slug' => 'blush', 'initials' => 'B', 'value' => 9 ),
        array( 'name' => 'Crave', 'slug' => 'crave', 'initials' => 'C', 'value' => 9 ),
        array( 'name' => 'DYSO', 'slug' => 'dyso', 'initials' => 'D', 'value' => 9 ),
        array( 'name' => 'Eye of Love', 'slug' => 'eye-of-love', 'initials' => 'EOL', 'value' => 9 ),
        array( 'name' => 'Fantasy Lingerie', 'slug' => 'fantasy-lingerie', 'initials' => 'FL', 'value' => 9 ),
        array( 'name' => 'FemmeFunn', 'slug' => 'femmefunn', 'initials' => 'F', 'value' => 9 ),
    );
}
